### ISSUE TITLE
How to use this package in react?

### ISSUE THREAD

**Issue by jagannath-swarnkar** [rhysd/react-embedded-browser#1]
I have installed this package but there is no clarity on how to use it in react.
May you please resolve it quickly.

**Comment by rhysd** [comment]
https://github.com/rhysd/react-embedded-browser/blob/master/README.md

**Comment by jagannath-swarnkar** [comment]
> https://github.com/rhysd/react-embedded-browser/blob/master/README.md

I checked and installed that but don't know how to use it and how can I use it in create-react-app application of react
